// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy1um2cUWKK0ilPA2PyyVR6iclXREIOcc',
    appId: '1:436142797279:web:5de8596512fd0b7c3f546a',
    messagingSenderId: '436142797279',
    projectId: 'guvenliyuvam-34544',
    authDomain: 'guvenliyuvam-34544.firebaseapp.com',
    databaseURL: 'https://guvenliyuvam-34544-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guvenliyuvam-34544.appspot.com',
    measurementId: 'G-ZFH7T4DEJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYKq_tW5u7xBw0lFKmJLRJzhFSlV98rs',
    appId: '1:436142797279:android:f3d72a3f6356fe173f546a',
    messagingSenderId: '436142797279',
    projectId: 'guvenliyuvam-34544',
    databaseURL: 'https://guvenliyuvam-34544-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guvenliyuvam-34544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw46-RD-EIYn_XyDYLwtgKCsvKNvoRxpE',
    appId: '1:436142797279:ios:5385725e94878c2d3f546a',
    messagingSenderId: '436142797279',
    projectId: 'guvenliyuvam-34544',
    databaseURL: 'https://guvenliyuvam-34544-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guvenliyuvam-34544.appspot.com',
    iosBundleId: 'com.example.sc24Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw46-RD-EIYn_XyDYLwtgKCsvKNvoRxpE',
    appId: '1:436142797279:ios:0c78664f914572553f546a',
    messagingSenderId: '436142797279',
    projectId: 'guvenliyuvam-34544',
    databaseURL: 'https://guvenliyuvam-34544-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guvenliyuvam-34544.appspot.com',
    iosBundleId: 'com.example.sc24Project.RunnerTests',
  );
}
